// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TravelPlan end to end', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').usingServer('http://localhost:4444/wd/hub').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TravelPlan end to end', async function() {
    // Test name: TravelPlan end to end
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1382x744 | 
    await driver.manage().window().setRect({ width: 1382, height: 744 })
    // 3 | click | css=.css-1hrv7oh | 
    await driver.findElement(By.css(".css-1hrv7oh")).click()
    // 4 | mouseOver | css=.css-1hrv7oh | 
    {
      const element = await driver.findElement(By.css(".css-1hrv7oh"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 5 | click | css=.chakra-input__group:nth-child(2) > .chakra-input | 
    await driver.findElement(By.css(".chakra-input__group:nth-child(2) > .chakra-input")).click()
    // 6 | type | css=.chakra-input__group:nth-child(2) > .chakra-input | udayangana98@gmail.com
    await driver.findElement(By.css(".chakra-input__group:nth-child(2) > .chakra-input")).sendKeys("udayangana98@gmail.com")
    // 7 | click | css=.chakra-input__group:nth-child(3) > .chakra-input | 
    await driver.findElement(By.css(".chakra-input__group:nth-child(3) > .chakra-input")).click()
    // 8 | type | css=.chakra-input__group:nth-child(3) > .chakra-input | Indunil@103
    await driver.findElement(By.css(".chakra-input__group:nth-child(3) > .chakra-input")).sendKeys("Indunil@103")
    // 9 | click | css=.css-8pcd7y | 
    await driver.findElement(By.css(".css-8pcd7y")).click()
    // 10 | mouseOver | css=.css-zq6wbi:nth-child(1) > .chakra-button | 
    {
      const element = await driver.findElement(By.css(".css-zq6wbi:nth-child(1) > .chakra-button"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 11 | mouseOut | css=.css-zq6wbi:nth-child(1) > .chakra-button | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 12 | click | css=.css-vuk4py | 
    await driver.findElement(By.css(".css-vuk4py")).click()
    // 13 | click | css=.css-zq6wbi:nth-child(1) > .chakra-button | 
    await driver.findElement(By.css(".css-zq6wbi:nth-child(1) > .chakra-button")).click()
    // 14 | click | css=.css-bjlvxy:nth-child(3) .chakra-checkbox:nth-child(3) > .chakra-checkbox__control | 
    await driver.findElement(By.css(".css-bjlvxy:nth-child(3) .chakra-checkbox:nth-child(3) > .chakra-checkbox__control")).click()
    // 15 | click | css=.css-bjlvxy:nth-child(3) .chakra-checkbox:nth-child(6) > .chakra-checkbox__control | 
    await driver.findElement(By.css(".css-bjlvxy:nth-child(3) .chakra-checkbox:nth-child(6) > .chakra-checkbox__control")).click()
    // 16 | click | css=.chakra-checkbox:nth-child(8) > .chakra-checkbox__control | 
    await driver.findElement(By.css(".chakra-checkbox:nth-child(8) > .chakra-checkbox__control")).click()
    // 17 | click | css=.chakra-stack:nth-child(4) > .chakra-button | 
    await driver.findElement(By.css(".chakra-stack:nth-child(4) > .chakra-button")).click()
    // 18 | click | css=.chakra-radio:nth-child(2) > .chakra-radio__control | 
    await driver.findElement(By.css(".chakra-radio:nth-child(2) > .chakra-radio__control")).click()
    // 19 | click | css=.css-1tzp4jb .chakra-button:nth-child(2) | 
    await driver.findElement(By.css(".css-1tzp4jb .chakra-button:nth-child(2)")).click()
    // 20 | click | css=.css-1tzp4jb .chakra-select | 
    await driver.findElement(By.css(".css-1tzp4jb .chakra-select")).click()
    // 21 | select | css=.css-1tzp4jb .chakra-select | label=3 Day
    {
      const dropdown = await driver.findElement(By.css(".css-1tzp4jb .chakra-select"))
      await dropdown.findElement(By.xpath("//option[. = '3 Day']")).click()
    }
    // 22 | click | css=.css-1tzp4jb .chakra-button:nth-child(2) | 
    await driver.findElement(By.css(".css-1tzp4jb .chakra-button:nth-child(2)")).click()
    // 23 | click | css=.css-1tzp4jb .chakra-select | 
    await driver.findElement(By.css(".css-1tzp4jb .chakra-select")).click()
    // 24 | select | css=.css-1tzp4jb .chakra-select | label=Buddhism
    {
      const dropdown = await driver.findElement(By.css(".css-1tzp4jb .chakra-select"))
      await dropdown.findElement(By.xpath("//option[. = 'Buddhism']")).click()
    }
    // 25 | click | css=.css-1tzp4jb .chakra-button:nth-child(2) | 
    await driver.findElement(By.css(".css-1tzp4jb .chakra-button:nth-child(2)")).click()
    // 26 | click | css=.css-1tzp4jb .chakra-checkbox:nth-child(1) > .chakra-checkbox__label | 
    await driver.findElement(By.css(".css-1tzp4jb .chakra-checkbox:nth-child(1) > .chakra-checkbox__label")).click()
    // 27 | click | css=.css-1tzp4jb .chakra-checkbox:nth-child(4) | 
    await driver.findElement(By.css(".css-1tzp4jb .chakra-checkbox:nth-child(4)")).click()
    // 28 | click | css=.css-1tzp4jb .chakra-checkbox:nth-child(5) | 
    await driver.findElement(By.css(".css-1tzp4jb .chakra-checkbox:nth-child(5)")).click()
    // 29 | click | css=.css-1tzp4jb > .css-bjlvxy | 
    await driver.findElement(By.css(".css-1tzp4jb > .css-bjlvxy")).click()
    // 30 | click | css=.css-1tzp4jb .chakra-button:nth-child(2) | 
    await driver.findElement(By.css(".css-1tzp4jb .chakra-button:nth-child(2)")).click()
    // 31 | click | css=.css-1tzp4jb .chakra-button:nth-child(2) | 
    await driver.findElement(By.css(".css-1tzp4jb .chakra-button:nth-child(2)")).click()
    // 32 | click | css=.css-1tzp4jb .chakra-button:nth-child(2) | 
    await driver.findElement(By.css(".css-1tzp4jb .chakra-button:nth-child(2)")).click()
    // 33 | mouseOver | css=.css-1tzp4jb .chakra-button:nth-child(2) | 
    {
      const element = await driver.findElement(By.css(".css-1tzp4jb .chakra-button:nth-child(2)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 34 | click | id=tabs-26--tab-1 | 
    await driver.findElement(By.id("tabs-26--tab-1")).click()
    // 35 | click | id=tabs-26--tab-0 | 
    await driver.findElement(By.id("tabs-26--tab-0")).click()
    // 36 | click | css=.chakra-button:nth-child(1) | 
    await driver.findElement(By.css(".chakra-button:nth-child(1)")).click()
    // 37 | runScript | window.scrollTo(0,3703.33349609375) | 
    await driver.executeScript("window.scrollTo(0,3703.33349609375)")
    // 38 | click | css=.chakra-stack:nth-child(3) .chakra-button:nth-child(1) | 
    await driver.findElement(By.css(".chakra-stack:nth-child(3) .chakra-button:nth-child(1)")).click()
    // 39 | click | css=.css-4q8vvp | 
    await driver.findElement(By.css(".css-4q8vvp")).click()
    // 40 | click | css=.chakra-stack:nth-child(20) > .chakra-button | 
    await driver.findElement(By.css(".chakra-stack:nth-child(20) > .chakra-button")).click()
    // 41 | click | css=.css-kz7tvw | 
    await driver.findElement(By.css(".css-kz7tvw")).click()
    // 42 | runScript | window.scrollTo(0,133.33334350585938) | 
    await driver.executeScript("window.scrollTo(0,133.33334350585938)")
    // 43 | click | css=.chakra-button:nth-child(2) | 
    await driver.findElement(By.css(".chakra-button:nth-child(2)")).click()
    // 44 | click | css=.css-jxg557 | 
    await driver.findElement(By.css(".css-jxg557")).click()
    // 45 | runScript | window.scrollTo(0,153.33334350585938) | 
    await driver.executeScript("window.scrollTo(0,153.33334350585938)")
    // 46 | runScript | window.scrollTo(0,5.555555820465088) | 
    await driver.executeScript("window.scrollTo(0,5.555555820465088)")
    // 47 | click | css=.css-13zlxqu:nth-child(1) .css-noppgp > .chakra-stack > .chakra-stack > .chakra-button | 
    await driver.findElement(By.css(".css-13zlxqu:nth-child(1) .css-noppgp > .chakra-stack > .chakra-stack > .chakra-button")).click()
    // 48 | click | id=menu-button-4 | 
    await driver.findElement(By.id("menu-button-4")).click()
    // 49 | click | css=.css-1ua73sh > svg | 
    await driver.findElement(By.css(".css-1ua73sh > svg")).click()
    // 50 | click | css=.chakra-icon:nth-child(5) > path | 
    await driver.findElement(By.css(".chakra-icon:nth-child(5) > path")).click()
    // 51 | click | css=.css-8pcd7y | 
    await driver.findElement(By.css(".css-8pcd7y")).click()
    // 52 | click | id=menu-button-4 | 
    await driver.findElement(By.id("menu-button-4")).click()
    // 53 | click | id=menu-list-4-menuitem-12 | 
    await driver.findElement(By.id("menu-list-4-menuitem-12")).click()
    // 54 | click | css=.css-13zlxqu:nth-child(1) > .chakra-stack > .chakra-button > svg | 
    await driver.findElement(By.css(".css-13zlxqu:nth-child(1) > .chakra-stack > .chakra-button > svg")).click()
    // 55 | click | css=.css-n45e6f | 
    await driver.findElement(By.css(".css-n45e6f")).click()
    // 56 | click | css=.css-oht7if | 
    await driver.findElement(By.css(".css-oht7if")).click()
    // 57 | click | css=.css-zq6wbi:nth-child(2) > .chakra-button | 
    await driver.findElement(By.css(".css-zq6wbi:nth-child(2) > .chakra-button")).click()
    // 58 | runScript | window.scrollTo(0,153.33334350585938) | 
    await driver.executeScript("window.scrollTo(0,153.33334350585938)")
    // 59 | click | css=.chakra-button:nth-child(1) | 
    await driver.findElement(By.css(".chakra-button:nth-child(1)")).click()
    // 60 | click | css=.pac-target-input | 
    await driver.findElement(By.css(".pac-target-input")).click()
    // 61 | sendKeys | css=.pac-target-input | ${KEY_DOWN}
    await driver.findElement(By.css(".pac-target-input")).sendKeys(Key.DOWN)
    // 62 | type | css=.pac-target-input | Kelaniya Raja Maha Viharaya, Peliyagoda, Sri Lanka
    await driver.findElement(By.css(".pac-target-input")).sendKeys("Kelaniya Raja Maha Viharaya, Peliyagoda, Sri Lanka")
    // 63 | sendKeys | css=.pac-target-input | ${KEY_ENTER}
    await driver.findElement(By.css(".pac-target-input")).sendKeys(Key.ENTER)
    // 64 | sendKeys | css=.pac-target-input | ${KEY_DOWN}
    await driver.findElement(By.css(".pac-target-input")).sendKeys(Key.DOWN)
    // 65 | type | css=.pac-target-input | Manelwatta Temple, Sri Lanka
    await driver.findElement(By.css(".pac-target-input")).sendKeys("Manelwatta Temple, Sri Lanka")
    // 66 | sendKeys | css=.pac-target-input | ${KEY_ENTER}
    await driver.findElement(By.css(".pac-target-input")).sendKeys(Key.ENTER)
    // 67 | click | css=.chakra-button:nth-child(4) | 
    await driver.findElement(By.css(".chakra-button:nth-child(4)")).click()
    // 68 | click | css=.chakra-button:nth-child(2) > svg | 
    await driver.findElement(By.css(".chakra-button:nth-child(2) > svg")).click()
    // 69 | click | css=.css-jxg557 | 
    await driver.findElement(By.css(".css-jxg557")).click()
    // 70 | runScript | window.scrollTo(0,0) | 
    await driver.executeScript("window.scrollTo(0,0)")
    // 71 | click | css=.css-13zlxqu:nth-child(1) .css-noppgp > .chakra-stack > .chakra-stack > .chakra-button | 
    await driver.findElement(By.css(".css-13zlxqu:nth-child(1) .css-noppgp > .chakra-stack > .chakra-stack > .chakra-button")).click()
    // 72 | click | id=menu-button-4 | 
    await driver.findElement(By.id("menu-button-4")).click()
    // 73 | click | id=menu-list-4-menuitem-12 | 
    await driver.findElement(By.id("menu-list-4-menuitem-12")).click()
    // 74 | click | css=.css-13zlxqu:nth-child(1) > .chakra-stack > .chakra-button > svg | 
    await driver.findElement(By.css(".css-13zlxqu:nth-child(1) > .chakra-stack > .chakra-button > svg")).click()
    // 75 | click | css=.css-n45e6f | 
    await driver.findElement(By.css(".css-n45e6f")).click()
    // 76 | click | css=.css-oht7if | 
    await driver.findElement(By.css(".css-oht7if")).click()
    // 77 | click | css=.chakra-stack > .chakra-button | 
    await driver.findElement(By.css(".chakra-stack > .chakra-button")).click()
    // 78 | runScript | window.scrollTo(0,133.33334350585938) | 
    await driver.executeScript("window.scrollTo(0,133.33334350585938)")
    // 79 | click | css=.css-oht7if | 
    await driver.findElement(By.css(".css-oht7if")).click()
    // 80 | runScript | window.scrollTo(0,1645.5555419921875) | 
    await driver.executeScript("window.scrollTo(0,1645.5555419921875)")
    // 81 | click | css=.css-1mlitlw | 
    await driver.findElement(By.css(".css-1mlitlw")).click()
    // 82 | click | css=.chakra-stack > .chakra-button | 
    await driver.findElement(By.css(".chakra-stack > .chakra-button")).click()
    // 83 | runScript | window.scrollTo(0,222.22222900390625) | 
    await driver.executeScript("window.scrollTo(0,222.22222900390625)")
    // 84 | click | id=tabs-118--tab-1 | 
    await driver.findElement(By.id("tabs-118--tab-1")).click()
    // 85 | click | id=tabs-118--tab-0 | 
    await driver.findElement(By.id("tabs-118--tab-0")).click()
    // 86 | click | id=menu-button-4 | 
    await driver.findElement(By.id("menu-button-4")).click()
    // 87 | click | id=menu-list-4-menuitem-10 | 
    await driver.findElement(By.id("menu-list-4-menuitem-10")).click()
    // 88 | click | css=.css-f6n2t5 | 
    await driver.findElement(By.css(".css-f6n2t5")).click()
    // 89 | click | css=.css-f6n2t5:nth-child(1) | 
    await driver.findElement(By.css(".css-f6n2t5:nth-child(1)")).click()
    // 90 | click | css=.css-1wlmk2s | 
    await driver.findElement(By.css(".css-1wlmk2s")).click()
    // 91 | click | id=menu-button-4 | 
    await driver.findElement(By.id("menu-button-4")).click()
    // 92 | click | id=menu-list-4-menuitem-10 | 
    await driver.findElement(By.id("menu-list-4-menuitem-10")).click()
    // 93 | click | css=.css-oht7if | 
    await driver.findElement(By.css(".css-oht7if")).click()
    // 94 | runScript | window.scrollTo(0,777.7777709960938) | 
    await driver.executeScript("window.scrollTo(0,777.7777709960938)")
    // 95 | click | css=.css-3yk3t0:nth-child(1) | 
    await driver.findElement(By.css(".css-3yk3t0:nth-child(1)")).click()
    // 96 | click | css=.css-oht7if | 
    await driver.findElement(By.css(".css-oht7if")).click()
    // 97 | click | css=.css-3yk3t0:nth-child(2) | 
    await driver.findElement(By.css(".css-3yk3t0:nth-child(2)")).click()
    // 98 | click | css=.chakra-image | 
    await driver.findElement(By.css(".chakra-image")).click()
    // 99 | runScript | window.scrollTo(0,11.111111640930176) | 
    await driver.executeScript("window.scrollTo(0,11.111111640930176)")
    // 100 | click | css=.css-0 > .chakra-button | 
    await driver.findElement(By.css(".css-0 > .chakra-button")).click()
  })
})
